version: '3.8'
services:
  web:
    image: php:8.0-apache
    container_name: php-apache-dev
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/web-start.sh:/usr/local/bin/docker-php-entrypoint
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    networks:
      - app-network
    entrypoint: ["/usr/local/bin/docker-php-entrypoint"]

  db:
    image: mariadb
    container_name: mariadb-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
